# Generated by Django 3.2.4 on 2021-07-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='slug',
        ),
    ]
