# Generated by Django 3.2.4 on 2021-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_instrument_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq',
            name='description',
            field=models.TextField(blank=True, default='none', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eq',
            name='frequency',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
