# Generated by Django 3.2.4 on 2021-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210729_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
