# Generated by Django 3.2.4 on 2021-07-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_eq_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq',
            name='description',
            field=models.TextField(blank=True, default='Description', max_length=250, null=True),
        ),
    ]
