# Generated by Django 3.2.4 on 2021-07-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_eq_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
